# Generated by Django 3.2.3 on 2021-06-03 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_clone', '0003_auto_20210603_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 18, 6, 14, 825375, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 18, 6, 14, 824734, tzinfo=utc)),
        ),
    ]
